name: saltstack-tools-formula
source: https://github.com/bechtoldt/saltstack-tools-formula
summary: SaltStack Formula to set up and configure a set of handy tools which are too simple/ small to dedicate individual formulas to
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
  - 'provide removing the tools/ packages, too (state)'
